# Generated by Django 6.0.5 on 2026-05-17 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневно'), ('every_2_days', 'Каждые 2 дня'), ('every_3_days', 'Каждые 3 дня'), ('every_4_days', 'Каждые 4 дня'), ('every_5_days', 'Каждые 5 дней'), ('every_6_days', 'Каждые 6 дней'), ('weekly', 'Еженедельно')], default='daily', max_length=20, verbose_name='Периодичность')),
                ('execution_time', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('related_habit', models.ForeignKey(blank=True, limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'db_table': 'habits',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='HabitExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('skipped', 'Пропущено'), ('pending', 'Ожидает')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Выполнение привычки',
                'verbose_name_plural': 'Выполнения привычек',
                'db_table': 'habit_executions',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_public'], name='habits_user_id_89704a_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['periodicity', 'time'], name='habits_periodi_da73a7_idx'),
        ),
        migrations.AddIndex(
            model_name='habitexecution',
            index=models.Index(fields=['habit', 'execution_date'], name='habit_execu_habit_i_f39a66_idx'),
        ),
        migrations.AddIndex(
            model_name='habitexecution',
            index=models.Index(fields=['status'], name='habit_execu_status_549c4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitexecution',
            unique_together={('habit', 'execution_date')},
        ),
    ]
